server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "health,info,metrics"
    jmx:
      exposure:
        include: "*"
  influx:
    metrics:
      export:
        db: spring-actuator
        enabled: true
        uri: http://localhost:8086
        auto-create-db: true
        consistency: one
        step: 5s
spring:
  application:
    name: hhplus-concert-reservation
  datasource:
    url: jdbc:mysql://localhost:3306/hhplus_concert_reservation?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      max-lifetime: 1800000
      idle-timeout: 30000
      connection-timeout: 30000
  sql:
    init:
      mode: always
      data-locations:
      - classpath:sql/data.sql
      schema-locations:
      - classpath:sql/schema.sql
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
        default_batch_fetch_size: 1000
        jdbc:
          batch_size: 1000
    show-sql: true
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379


