global:
  scrape_interval: 10s # 10초 마다 Metric을 Pulling
  scrape_timeout: 10s # 10초 이상 Metric을 Pulling 하지 않으면 Timeout
  evaluation_interval: 2m # rule 을 얼마나 빈번하게 검증하는지 설정

scrape_configs:
  - job_name: 'spring-actuator-prometheus'
    metrics_path: '/actuator/prometheus' # Application prometheus endpoint
    static_configs:
      - targets: ['host.docker.internal:8080'] # Application host:port
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ] # Applicati